### ISSUE TITLE
Manual measures

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#12]
##List of possible manual measures
* Emergency restore dry run
* Check webserver disk space
* Verify monitoring
* Verify backups are copied offsite 
* Verify backups are restorable
@gregelin anything to add to this list?

##Data schema
Measure: 
* Title
* Body - The Process, "issue template"/description
* Frequency -int
* Datetime (last time run)
* Submission - the last Submission REMOVE

GET /sites/:siteId/measures/:measureId
POST /sites/:siteId/measures/:measureId

Submission: 
* Measure id
* User id (down the road)
* Name
* Datetime
* body: Submission text
* data: Submission data (down the road)

POST /sites/:siteId/measures/:measureId/submissions/:submissionID
GET /sites/:siteId/measures/:measureId/submissions

GET /sites/:siteId/measures/submissions
* All submissions for a :siteId ordered by datetime DESC (show 10 or 20)

##Rough mockup
[govready-manual-measures.pdf](https://github.com/GovReady/GovReady-Drupal-Agent/files/275187/govready-manual-measures.pdf)

**Comment by gregelin** [comment]
@jlyon I think your manual measure list is a good start. Especially like the Emergency restore dry run.

Other ideas:
- cyber security awareness training
- incident response practice
- log reviews
- Team calls?

**Comment by jlyon** [comment]
Thanks!

**Comment by jlyon** [comment]
Prepopulated measures:

* Remove unused accounts
* log reviews
* Verify backups are copied offsite
* Verify backups are restorable
* cyber security awareness training - links out to GovReady docs

**Comment by jlyon** [comment]
From Alex and Jeff call:

- [ ] GET http://plugin.govready.com/v1.0/sites/5744afb69c86af4c3be5b19c/measures/:measureID - Just returns Measure data
- [ ] Add due field. On measure create/save, update based on datetime, frequency
- [ ] When a Submmisison is saved, update the Measure datetime to now
- [ ] GET http://plugin.govready.com/v1.0/sites/5744afb69c86af4c3be5b19c/measures - includes measure id, title, submission, ordered by submission.due
- [ ] PATCH http://plugin.govready.com/v1.0/sites/5744afb69c86af4c3be5b19c/measures/:measureID
- [ ] PATCH http://plugin.govready.com/v1.0/sites/5744afb69c86af4c3be5b19c/measures/:measureID/submissions/:submissionId

**Comment by aschmoe** [comment]
@jlyon unclear if "When a Submmisison is saved, update the Measure datetime to now" is App or API side... I'm leaning towards backend.

**Comment by jlyon** [comment]
Yes, I'm thinking everything by the last one tagged @aschmoe is backend.

**Comment by aschmoe** [comment]
@jlyon one more route that would be nice is a recent submissions request.  

submissions/recent

As that would allow client to avoid calling ```measures.each( measures/:id/submissions...  )``` on load

**Comment by jlyon** [comment]
@aschmoe added as /sites/:siteId/submissions

**Comment by jlyon** [comment]
* Greg\'s (forward slash)
* wipe out value after submission
* field labels

**Comment by aschmoe** [comment]
@jlyon Measures currently doesn't have a delete route in the API... thoughts?  Seems like we should be able to delete those
