### ISSUE TITLE
Example websites

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#17]

**Comment by jlyon** [comment]
@gregelin MySQL was down again on 107.170.3.94.  I think the memory might be too low for it to consistently stay up, so I put the two sites up on an Albatross server.  If you create two subdomain records, I can set these up on govready (these will replace the albatrossdemos with govready in the urls below:

wordpress.govready IN A 192.241.208.128
drupal.govready IN A 192.241.208.128

Thanks,
Jeff


Drupal:
* url: http://drupal.govready.albatrossdemos.com/
* u: admin
* p: czvoSl97xbC6
* dashboard: Reports > GovReady Dashboard (in toolbar): http://drupal.govready.albatrossdemos.com/admin/reports/govready


Wordpress:
* url: http://wordpress.govready.albatrossdemos.com/
* u: admin
* p: hr6#8mnmJP0aGqW7BE
* GovReady  (in left sidebar): http://wordpress.govready.albatrossdemos.com/wp-admin/admin.php?page=govready

**Comment by jlyon** [comment]
Note: I updated the original post @gregelin

**Comment by gregelin** [comment]
Thanks!

**Comment by jlyon** [comment]
Yep. I edited the post so see
https://github.com/GovReady/GovReady-Drupal-Agent/issues/17 for more
details.

**Comment by gregelin** [comment]
@jlyon Both look just great. Thanks for standing up. Manual Tasks are excellent, simple and elegant how the template self-describes the task.

I've changed password on both and put the passwords in passpack.

**Comment by jlyon** [comment]
Great!  Sorry, I missed this alert in the morning and reset the WordPress password. I reset it to what you have in Passpack.
