### ISSUE TITLE
Move hosting for this module to Drupal.org

### ISSUE THREAD

**Issue by openprivacy** [GovReady/GovReady-Drupal-Agent#20]
It will make the module much more generally useful if/when hosted at d.o.

For a how to, see: https://www.drupal.org/node/7765

I can help with the process if needed/desired.

**Comment by jlyon** [comment]
Created on https://www.drupal.org/project/govready. I also created a GovReady d.o. Organization (to link it to the project as a supporting organization): https://www.drupal.org/govready

**Comment by jlyon** [comment]
I created a development release on  https://www.drupal.org/project/govready.

**Comment by openprivacy** [comment]
sweet! added the link to a conference handout
