### ISSUE TITLE
Counts incorrect?

### ISSUE THREAD

**Issue by openprivacy** [GovReady/GovReady-Drupal-Agent#22]
On a test site I have locally, I have the GovReady agent reports 6 modules needing security updates but only one does as shown by:
```
» drush upc -n --security-only
Update information last refreshed: July 8, 2016
 Name           Installed Version  Proposed version  Message                   
 Views (views)  7.x-3.11           7.x-3.14          SECURITY UPDATE available
```

Similarly, 42 "super admins" are reported but there are 17:
```
» drush sqlq "SELECT COUNT(uid) FROM users_roles WHERE rid = 9"
count(uid)
17
```

**Comment by jlyon** [comment]
We have cleaned up the module status reporting logic and tested it on a few different sites and some standard Drupal distributions and the module counts are looking much better now.

> Similarly, 42 "super admins" are reported but there are 17:
Super admins are users that have the "administer site configuration" permission.

Run `drush govready-collect all` to send the latest data from Drupal to the GovReady API (after pulling the latest code in the govready module).
