### ISSUE TITLE
Demo server

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#25]
- [ ] Host at *.govready.com
- [ ] Multiple users, plugins, databases, etc
- [ ] Create account for a demo user (u=demo, p=demo)

**Comment by jlyon** [comment]
@gregelin Is it ok if we leave these demo instances on the same server that they are currently on (http://drupal.govready.albatrossdemos.com/). If so, can you create subdomain DNS records on govready.com, and I'll set up the rest:
```
drupal.plugin IN A 192.241.208.128
wordpress.plugin IN A 192.241.208.128
```

**Comment by jlyon** [comment]
@gregelin DNS settings:
```
drupal.plugin IN A 192.241.208.128
wordpress.plugin IN A 192.241.208.128
```

**Comment by gregelin** [comment]
@jlyon 

http://drupal.plugin.govready.com and http://wordpress.plugin.com are live

**Comment by gregelin** [comment]
@jlyon 

demo/demo working for drupal.plugin.govready.com but not working for wordpress.plugin.govready.com

Also, does hourly reset for drupal.plugin.govready.com also reset ALL the content drupal (e.g., remove any created pages?)

**Comment by jlyon** [comment]
@gregelin I set up the demo:demo user on http://wordpress.plugin.govready.com and updated the homepage language to give more of an explanation.

I also updated the demo link on https://www.drupal.org/project/govready to point to the new url.
