### ISSUE TITLE
Dashboard loading slowly, not all widgets loading

### ISSUE THREAD

**Issue by gregelin** [GovReady/GovReady-Drupal-Agent#27]
Signed into Drupal dashboard this morning and took long time to load. Finally hit reload and some widgets appeared. Pic:

<img width="1375" alt="screen shot 2016-07-18 at 9 32 07 am" src="https://cloud.githubusercontent.com/assets/24979/16916460/eebd79d0-4cca-11e6-8112-aa062cd95bf3.png">

**Comment by jlyon** [comment]
I will take a look at this today.

**Comment by jlyon** [comment]
- [ ] Monitor endpoints aren't working
- [ ] Disabled modules are appearing under Vulnerabilities
- [ ] Increase timeout on /vulnerabilities @aschmoe
- [ ] Thorough testing on startup endpoints (Monitor)

**Comment by jlyon** [comment]
Fixed these issues yesterday and last night.
