### ISSUE TITLE
Dashboard: "Drupal core is up-to-date" always shows

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#29]
To replicate:

- Test module with drupal-7.44
Result: The top-left Plugin box correctly shows that there is a security update available for Drupal, but the green "Drupal core is up to date" message still appears under vulnerabilities
![govready dashboard - site-install 1](https://cloud.githubusercontent.com/assets/550909/16939899/82dace64-4d3a-11e6-9573-f6734690cdf7.jpg)

**Comment by aschmoe** [comment]
Jeff could you paste the ```/govready/api?action=govready_proxy&endpoint=/sites/SITEIDNUMBER/vulnerabilities&method=GET``` vs ```/govready/api?action=govready_proxy&endpoint=/sites/SITEIDNUMBER/plugins&method=GET```
here?

**Comment by jlyon** [comment]
This has been fixed with an update to the /plugins output.
