### ISSUE TITLE
CSS: Adding contacts, buttons cut off

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#33]
URL: http://drupal.govready.albatrossdemos.com/admin/reports/govready#/dashboard/Contacts?_k=vitpty

![screenshot from 2016-07-19 14 32 11](https://cloud.githubusercontent.com/assets/550909/16967426/aff714b0-4dbd-11e6-898a-691b9a57f25e.png)

**Comment by aschmoe** [comment]
![govready dashboard - govready drupal dashboard](https://cloud.githubusercontent.com/assets/1634686/16968054/5325c692-4dc1-11e6-96c2-c7aec3a92189.jpg)

Did you do something to make that happen?  Zoom, clicking or something?

**Comment by jlyon** [comment]
Hmm, seems to be fixed for me now.  Don't think I did anything to make it happen.
