### ISSUE TITLE
GovCon submission

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#7]
Next week? (from call 5/17)

**Comment by gregelin** [comment]
@jlyon Yes, we should do a submission. Can you draft today? Submission due today.

**Comment by jlyon** [comment]
Alex is going to start drafting a submission today.  They aren't actually due until next Weds, it looks like https://www.drupalgovcon.org/drupal-govcon-2016

**Comment by jlyon** [comment]
https://docs.google.com/a/proudcity.com/document/d/1ZO7H_slC6reiaZbfxtT_MwPgpAH7rnGcvc4RrIVFJQY/edit?usp=sharing
